sudo: required

language: python

addons:
    apt:
        packages:
            - docker-ce

services:
    - docker

before_install:
    - docker build --force-rm -f Dockerfile -t "agavecli-dev" .

script:
    - docker run --rm -v "$PWD":/agave-cli agavecli-dev /agave-cli/tests/hack/run-integration-tests.run
